import Navbar from '@/components/navbar'
import Head from 'next/head'
import {BsPencilFill} from "react-icons/bs"
export default function Home() {  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <div>
          <h2>wilko blogging website</h2>
            <BsPencilFill size={"10rem"}></BsPencilFill>
          <div>
             this is a general purpose blogging website
          </div>
        </div>
        <div>
          <p>recommened blogs</p>
        </div>
        <div>
          <div>
            blog name and description
          </div>
          <div>
            blog name and description
          </div>
          <div>
            blog name and description
          </div>
          <div>
            blog name and description
          </div>
          <div>
            blog name and description
          </div>
          <div>
            blog name and description
          </div>
        </div>
      </main>
    </>
  )
}
