import BlogCards from '@/components/blogCards';
import Navbar from '@/components/navbar';
import Head from 'next/head';
import {BsPencilFill} from "react-icons/bs";
import styles from "../styles/home.module.css";

export default function Home() {  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <div className={styles.bannerShadow}>
          <div className={styles.banner}>
            <h2 className={styles.bannerTittle}>wilko <br>
            </br>blogging
            <br></br>
            website</h2>
              <BsPencilFill size={"40rem"} className={styles.pencil}></BsPencilFill>
            <div className={styles.bannerdescription}>
              this blog was made by wilko 
            </div>
          </div>
        </div>
        <div className={styles.recommened}>
          <p>recommened blogs:</p>
        </div>
        <div className={styles.cards}>
          <BlogCards/>
          <BlogCards/>
          <BlogCards/>
          <BlogCards/>
          <BlogCards/>
          <BlogCards/>
        </div>
      </main>
    </>
  )
}
